### ISSUE TITLE
-Update sign-in modal 

### ISSUE THREAD

**Issue by ACME-Evolved** [ACME-Evolved/Application#12]
## Problem

As a user, I want to be able to easily invite my colleagues to use ACME. I want to be able to either invite them directly with their email address or send them a link so they can connect their account.

## Tasks
- [x] remove `add users` friction point
- [x] add bulk invite or provide a direct link to ACME. 
- [ ] Users can manually send invites at an individual level.
- [ ] Run test
